---
- hosts: dev
  become: True
  tasks:
    - name: Update and upgrade apt packages
      apt:
      upgrade: yes
      update_cache: yes
      
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
